import { sql, type Kysely } from 'kysely'

// The whole schema in one migration: the product has no production Postgres yet,
// so there is nothing to migrate incrementally from. Later changes get their own
// numbered file.
export const initial = {
  async up(db: Kysely<unknown>): Promise<void> {
    await db.schema.createType('visibility').asEnum(['public', 'unlisted', 'deleted']).execute()
    await db.schema.createType('problem_type').asEnum(['choice', 'fill_in_blank']).execute()
    await db.schema.createType('user_role').asEnum(['user', 'admin', 'setter']).execute()
    await db.schema.createType('gender').asEnum(['male', 'female', 'unspecified']).execute()
    await db.schema.createType('comment_target').asEnum(['blog', 'problem', 'solution']).execute()
    await db.schema.createType('vote_target').asEnum(['blog', 'comment']).execute()

    await db.schema.createTable('country')
      .addColumn('code', 'char(2)', (c) => c.primaryKey())
      .addColumn('name', 'text', (c) => c.notNull())
      .execute()

    await db.schema.createTable('user')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('username', 'text', (c) => c.notNull())
      .addColumn('full_name', 'text', (c) => c.notNull().defaultTo(''))
      .addColumn('email', 'text', (c) => c.notNull())
      .addColumn('password_hash', 'text')
      .addColumn('role', sql`user_role`, (c) => c.notNull().defaultTo('user'))
      .addColumn('rating', 'integer', (c) => c.notNull().defaultTo(0))
      .addColumn('contribution_points', 'integer', (c) => c.notNull().defaultTo(0))
      .addColumn('country_code', 'char(2)')
      .addColumn('gender', sql`gender`, (c) => c.notNull().defaultTo('unspecified'))
      .addColumn('birthday', 'date')
      .addColumn('img_url', 'text')
      .addColumn('email_validated', 'boolean', (c) => c.notNull().defaultTo(false))
      .addColumn('registered_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .addColumn('last_online_at', 'timestamptz')
      .execute()
    // Usernames and emails compare case-insensitively, so uniqueness must too --
    // a plain unique index would let "Omar" and "omar" both register.
    await sql`create unique index user_username_lower_key on "user" (lower(username))`.execute(db)
    await sql`create unique index user_email_lower_key on "user" (lower(email))`.execute(db)
    await sql`create unique index user_legacy_id_key on "user" (legacy_id) where legacy_id is not null`.execute(db)
    await sql`create index user_rating_idx on "user" (rating desc)`.execute(db)

    await db.schema.createTable('session')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('user_id', 'text', (c) => c.notNull().references('user.id').onDelete('cascade'))
      .addColumn('expires_at', 'timestamptz', (c) => c.notNull())
      .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .execute()
    await sql`create index session_user_idx on session (user_id)`.execute(db)

    await db.schema.createTable('auth_token')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('user_id', 'text', (c) => c.notNull().references('user.id').onDelete('cascade'))
      .addColumn('kind', 'text', (c) => c.notNull())
      .addColumn('token_hash', 'text', (c) => c.notNull())
      .addColumn('expires_at', 'timestamptz', (c) => c.notNull())
      .addColumn('used_at', 'timestamptz')
      .execute()
    await sql`create unique index auth_token_hash_key on auth_token (token_hash)`.execute(db)

    await db.schema.createTable('contest')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('slug', 'text', (c) => c.notNull().unique())
      .addColumn('title', 'text', (c) => c.notNull())
      .addColumn('author_id', 'text', (c) => c.notNull().references('user.id'))
      .addColumn('starts_at', 'timestamptz', (c) => c.notNull())
      .addColumn('length_minutes', 'integer', (c) => c.notNull())
      .addColumn('allowed_attempts', 'integer', (c) => c.notNull().defaultTo(3))
      .addColumn('visibility', sql`visibility`, (c) => c.notNull().defaultTo('public'))
      .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .addColumn('updated_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .execute()
    await sql`create unique index contest_legacy_id_key on contest (legacy_id) where legacy_id is not null`.execute(db)
    await sql`create index contest_live_idx on contest (starts_at desc) where visibility <> 'deleted'`.execute(db)

    await db.schema.createTable('problem')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('slug', 'text', (c) => c.notNull().unique())
      .addColumn('title', 'text', (c) => c.notNull())
      .addColumn('type', sql`problem_type`, (c) => c.notNull().defaultTo('choice'))
      .addColumn('author_id', 'text', (c) => c.notNull().references('user.id'))
      .addColumn('writer_id', 'text', (c) => c.notNull().references('user.id'))
      .addColumn('description', 'text', (c) => c.notNull().defaultTo(''))
      .addColumn('solution', 'text', (c) => c.notNull().defaultTo(''))
      .addColumn('correct_option', 'text', (c) => c.notNull().defaultTo(''))
      .addColumn('visibility', sql`visibility`, (c) => c.notNull().defaultTo('public'))
      .addColumn('approved', 'boolean', (c) => c.notNull().defaultTo(false))
      .addColumn('points', 'integer', (c) => c.notNull().defaultTo(500))
      .addColumn('solved_count', 'integer', (c) => c.notNull().defaultTo(0))
      .addColumn('number_of_attempts', 'integer', (c) => c.notNull().defaultTo(0))
      .addColumn('contest_id', 'text', (c) => c.references('contest.id').onDelete('set null'))
      .addColumn('order_index', 'integer', (c) => c.notNull().defaultTo(0))
      .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .addColumn('updated_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .execute()
    await sql`create unique index problem_legacy_id_key on problem (legacy_id) where legacy_id is not null`.execute(db)
    await sql`create index problem_public_idx on problem (solved_count desc) where visibility = 'public'`.execute(db)
    await sql`create index problem_contest_idx on problem (contest_id, order_index) where contest_id is not null`.execute(db)

    await db.schema.createTable('problem_option')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('problem_id', 'text', (c) => c.notNull().references('problem.id').onDelete('cascade'))
      .addColumn('content', 'text', (c) => c.notNull())
      .addColumn('visibility', sql`visibility`, (c) => c.notNull().defaultTo('public'))
      .addColumn('order_index', 'integer', (c) => c.notNull().defaultTo(0))
      .execute()
    await sql`create index problem_option_problem_idx on problem_option (problem_id, order_index)`.execute(db)

    await db.schema.createTable('tag')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('name', 'text', (c) => c.notNull().unique())
      .addColumn('description', 'text')
      .execute()

    await db.schema.createTable('problem_tag')
      .addColumn('problem_id', 'text', (c) => c.notNull().references('problem.id').onDelete('cascade'))
      .addColumn('tag_id', 'text', (c) => c.notNull().references('tag.id').onDelete('cascade'))
      .addPrimaryKeyConstraint('problem_tag_pk', ['problem_id', 'tag_id'])
      .execute()

    await db.schema.createTable('problem_tutorial_access')
      .addColumn('user_id', 'text', (c) => c.notNull().references('user.id').onDelete('cascade'))
      .addColumn('problem_id', 'text', (c) => c.notNull().references('problem.id').onDelete('cascade'))
      .addColumn('unlocked_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .addPrimaryKeyConstraint('problem_tutorial_access_pk', ['user_id', 'problem_id'])
      .execute()

    await db.schema.createTable('contest_register')
      .addColumn('contest_id', 'text', (c) => c.notNull().references('contest.id').onDelete('cascade'))
      .addColumn('user_id', 'text', (c) => c.notNull().references('user.id').onDelete('cascade'))
      .addColumn('registered_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .addPrimaryKeyConstraint('contest_register_pk', ['contest_id', 'user_id'])
      .execute()

    await db.schema.createTable('submission')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('user_id', 'text', (c) => c.notNull().references('user.id').onDelete('cascade'))
      .addColumn('problem_id', 'text', (c) => c.notNull().references('problem.id').onDelete('cascade'))
      .addColumn('answer', 'text', (c) => c.notNull())
      .addColumn('correct', 'boolean', (c) => c.notNull().defaultTo(false))
      .addColumn('blind', 'boolean', (c) => c.notNull().defaultTo(false))
      .addColumn('submitted_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .execute()
    await sql`create unique index submission_legacy_id_key on submission (legacy_id) where legacy_id is not null`.execute(db)
    await sql`create index submission_user_problem_idx on submission (user_id, problem_id, submitted_at)`.execute(db)
    await sql`create index submission_recent_idx on submission (submitted_at desc)`.execute(db)

    await db.schema.createTable('rating_change')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('user_id', 'text', (c) => c.notNull().references('user.id').onDelete('cascade'))
      .addColumn('contest_id', 'text', (c) => c.notNull().references('contest.id').onDelete('cascade'))
      .addColumn('rank', 'integer', (c) => c.notNull())
      .addColumn('new_rating', 'integer', (c) => c.notNull())
      .execute()
    await sql`create unique index rating_change_user_contest_key on rating_change (user_id, contest_id)`.execute(db)
    await sql`create unique index rating_change_legacy_id_key on rating_change (legacy_id) where legacy_id is not null`.execute(db)

    await db.schema.createTable('blog_subject')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('title', 'text', (c) => c.notNull())
      .addColumn('order_index', 'integer', (c) => c.notNull().defaultTo(0))
      .execute()

    await db.schema.createTable('blog_category')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('slug', 'text', (c) => c.notNull().unique())
      .addColumn('title', 'text', (c) => c.notNull())
      .addColumn('description', 'text')
      .addColumn('subject_id', 'text', (c) => c.notNull().references('blog_subject.id'))
      .addColumn('order_index', 'integer', (c) => c.notNull().defaultTo(0))
      .execute()

    await db.schema.createTable('blog')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('title', 'text', (c) => c.notNull())
      .addColumn('content', 'text', (c) => c.notNull().defaultTo(''))
      .addColumn('author_id', 'text', (c) => c.notNull().references('user.id'))
      .addColumn('category_id', 'text', (c) => c.notNull().references('blog_category.id'))
      .addColumn('visibility', sql`visibility`, (c) => c.notNull().defaultTo('public'))
      .addColumn('announcement', 'boolean', (c) => c.notNull().defaultTo(false))
      .addColumn('up_votes', 'integer', (c) => c.notNull().defaultTo(0))
      .addColumn('down_votes', 'integer', (c) => c.notNull().defaultTo(0))
      .addColumn('comment_count', 'integer', (c) => c.notNull().defaultTo(0))
      .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .addColumn('last_activity_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .execute()
    await sql`create unique index blog_legacy_id_key on blog (legacy_id) where legacy_id is not null`.execute(db)
    await sql`create index blog_activity_idx on blog (last_activity_at desc) where visibility <> 'deleted'`.execute(db)

    await db.schema.createTable('comment')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('target', sql`comment_target`, (c) => c.notNull())
      .addColumn('target_id', 'text', (c) => c.notNull())
      .addColumn('parent_id', 'text', (c) => c.references('comment.id'))
      .addColumn('author_id', 'text', (c) => c.notNull().references('user.id'))
      .addColumn('content', 'text', (c) => c.notNull())
      .addColumn('visibility', sql`visibility`, (c) => c.notNull().defaultTo('public'))
      .addColumn('up_votes', 'integer', (c) => c.notNull().defaultTo(0))
      .addColumn('down_votes', 'integer', (c) => c.notNull().defaultTo(0))
      .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .execute()
    await sql`create unique index comment_legacy_id_key on comment (legacy_id) where legacy_id is not null`.execute(db)
    await sql`create index comment_target_idx on comment (target, target_id, created_at)`.execute(db)

    await db.schema.createTable('vote')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('target', sql`vote_target`, (c) => c.notNull())
      .addColumn('target_id', 'text', (c) => c.notNull())
      .addColumn('user_id', 'text', (c) => c.notNull().references('user.id').onDelete('cascade'))
      .addColumn('up_vote', 'boolean', (c) => c.notNull())
      .execute()
    // One vote per user per target -- the legacy data has duplicates, which the
    // migration is required to collapse rather than carry over.
    await sql`create unique index vote_unique_key on vote (user_id, target, target_id)`.execute(db)
    await sql`create unique index vote_legacy_id_key on vote (legacy_id) where legacy_id is not null`.execute(db)

    await db.schema.createTable('badge')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('title', 'text', (c) => c.notNull())
      .addColumn('description', 'text')
      .addColumn('img_url', 'text')
      .addColumn('deleted', 'boolean', (c) => c.notNull().defaultTo(false))
      .execute()

    await db.schema.createTable('badge_user')
      .addColumn('badge_id', 'text', (c) => c.notNull().references('badge.id').onDelete('cascade'))
      .addColumn('user_id', 'text', (c) => c.notNull().references('user.id').onDelete('cascade'))
      .addColumn('awarded_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .addPrimaryKeyConstraint('badge_user_pk', ['badge_id', 'user_id'])
      .execute()

    await db.schema.createTable('notification')
      .addColumn('id', 'text', (c) => c.primaryKey())
      .addColumn('legacy_id', 'integer')
      .addColumn('user_id', 'text', (c) => c.notNull().references('user.id').onDelete('cascade'))
      .addColumn('content', 'text', (c) => c.notNull())
      .addColumn('link', 'text')
      .addColumn('read', 'boolean', (c) => c.notNull().defaultTo(false))
      .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
      .execute()
    await sql`create index notification_user_idx on notification (user_id, created_at desc)`.execute(db)
  },

  async down(db: Kysely<unknown>): Promise<void> {
    for (const t of ['notification', 'badge_user', 'badge', 'vote', 'comment', 'blog',
      'blog_category', 'blog_subject', 'rating_change', 'submission', 'contest_register',
      'problem_tutorial_access', 'problem_tag', 'tag', 'problem_option', 'problem',
      'contest', 'auth_token', 'session', 'user', 'country']) {
      await db.schema.dropTable(t).ifExists().cascade().execute()
    }
    for (const t of ['vote_target', 'comment_target', 'gender', 'user_role', 'problem_type', 'visibility']) {
      await db.schema.dropType(t).ifExists().execute()
    }
  },
}
